default_model: llama3.2:3b

models:
  - name: mistral-nemo:12b
    provider: ollama
    model_params:
      temperature: 0.0
      max_tokens: 80
  - name: llama3.2:3b
    provider: ollama
    model_params:
      temperature: 0.0
      max_tokens: 80
  - name: minimax/minimax-m2.5:free
    provider: openrouter
    model_params:
      temperature: 0.0
      max_tokens: 1000
      top_p: 1.0
      extra_body:
        reasoning:
          effort: low
  - name: google/gemma-3-27b-it:free
    provider: openrouter
    model_params:
      temperature: 0.0
      max_tokens: 1000
      top_p: 1.0
  - name: meta-llama/llama-3.3-70b-instruct:free
    provider: openrouter
    model_params:
      temperature: 0.0
      max_tokens: 1000
      top_p: 1.0
  - name: qwen/qwen3-next-80b-a3b-instruct:free
    provider: openrouter
    model_params:
      temperature: 0.0
      max_tokens: 1000
      top_p: 1.0